### ISSUE TITLE
Error when trying to run evaluation code

### ISSUE THREAD

**Issue by torsadesdu** [birdortyedi/DeNIM#3]
I get an error when running the evaluation code you provided. Please advise how to correct it. Thank you. 

Traceback (most recent call last):
  File "C:\DeNIM-main\main.py", line 18, in <module>
    fire.Fire(run)
  File "C:\DeNIM-main\venv39\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\DeNIM-main\venv39\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\DeNIM-main\venv39\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\DeNIM-main\main.py", line 13, in run
    runner = AWBCorrectionTester(cfg)
  File "C:\DeNIM-main\engine\tester.py", line 23, in __init__
    self.dataset = dataset_getter(self.DATASET_NAME)(root=self.DATASET_ROOT, transform=self.transform)
  File "C:\DeNIM-main\dataset\awb.py", line 39, in __init__
    self.GTs = list((Path(root) / "GTs").iterdir())
  File "C:\python39\lib\pathlib.py", line 1160, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] The specified path can not be found。: '\\media\\birdortyedi\\e5042b8f-ca5e-4a22-ac68-7e69ff648bc4\\RenderedWB\\GTs'

**Comment by birdortyedi** [comment]
Of course, you should change the data path accordingly.

After downloading and processing the data, you should change DATASET_ROOT with yours. You can find the data and instructions for processing it in https://github.com/mahmoudnafifi/WB_sRGB/
